package eu.napcode.android_for_dummies.base

var ANIMATION_STANDARD_DURATION = 1000L
var ANIMATION_SHORT_DURATION = 500L
var ANIMATION_LONG_DURATION = 1500L

var ANIMATION_STANDARD_DELAY = 300L
var ANIMATION_SHORT_DELAY = 150L
var ANIMATION_LONG_DELAY = 600L